mappings:
  MetaFieldsExtension: gorriecoe\Meta\Extensions\MetaFieldsExtension
  MetaSiteTreeExtension: gorriecoe\Meta\Extensions\MetaSiteTreeExtension
  MetaTagExtension: gorriecoe\Meta\Extensions\MetaTagExtension
