---
Name: metaconfig
Only:
  moduleexists: 'silverstripe/cms'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - gorriecoe\Meta\Extensions\MetaFieldsExtension
    - gorriecoe\Meta\Extensions\MetaTagExtension
    - gorriecoe\Meta\Extensions\MetaSiteTreeExtension
---
Only:
  moduleexists: 'silverstripe/siteconfig'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - gorriecoe\Meta\Extensions\MetaFieldsExtension
